// <auto-generated />
using GeekShopping.ProductApi.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductApi.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20240210211443_TabelaProdutos")]
    partial class TabelaProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductApi.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CATEGORY");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("IMAGE_URL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NAME");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("PRICE");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("SIZE");

                    b.HasKey("Id");

                    b.ToTable("TB_PRODUCT");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            Category = "R-shirts",
                            Description = "Mario T-Shirt",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fboutiquemario.fr%2Fvetement%2Ftshirt%2Fsuper-mario-ds&psig=AOvVaw171sMWTgVHaUIhEiKndWLR&ust=1705000045534000&source=images&cd=vfe&ved=0CBIQjRxqFwoTCNjysqnC04MDFQAAAAAdAAAAABAE",
                            Name = "Mario T-Shirt",
                            Price = 69.900000000000006,
                            Size = "M"
                        },
                        new
                        {
                            Id = 3L,
                            Category = "R-shirts",
                            Description = "Mario T-Shirt",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fboutiquemario.fr%2Fvetement%2Ftshirt%2Fsuper-mario-ds&psig=AOvVaw171sMWTgVHaUIhEiKndWLR&ust=1705000045534000&source=images&cd=vfe&ved=0CBIQjRxqFwoTCNjysqnC04MDFQAAAAAdAAAAABAE",
                            Name = "Turtle T-Shirt",
                            Price = 89.900000000000006,
                            Size = "G"
                        },
                        new
                        {
                            Id = 4L,
                            Category = "R-shirts",
                            Description = "Mario T-Shirt",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fboutiquemario.fr%2Fvetement%2Ftshirt%2Fsuper-mario-ds&psig=AOvVaw171sMWTgVHaUIhEiKndWLR&ust=1705000045534000&source=images&cd=vfe&ved=0CBIQjRxqFwoTCNjysqnC04MDFQAAAAAdAAAAABAE",
                            Name = "Princesa T-Shirt",
                            Price = 99.900000000000006,
                            Size = "M"
                        },
                        new
                        {
                            Id = 5L,
                            Category = "R-shirts",
                            Description = "Mario T-Shirt",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fboutiquemario.fr%2Fvetement%2Ftshirt%2Fsuper-mario-ds&psig=AOvVaw171sMWTgVHaUIhEiKndWLR&ust=1705000045534000&source=images&cd=vfe&ved=0CBIQjRxqFwoTCNjysqnC04MDFQAAAAAdAAAAABAE",
                            Name = "Luigi T-Shirt",
                            Price = 169.90000000000001,
                            Size = "GG"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
